{{- if .Values.serviceAccounts.master.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    snappyflow/compname: elastic
    snappyflow/appname: prodenv-stage
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    component: "{{ .Values.master.name }}"
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "elasticsearch.master.fullname" . }}
{{- end }}
